CREATE TABLE artists (
  artist_id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  artist_name varchar(255) UNIQUE NOT NULL,
  birthday date NOT NULL,
  birthplace varchar(255) NOT NULL,
  is_alive bool NOT NULL DEFAULT true
);